### ISSUE TITLE
Remove 'xunit' dependency and depend on 'xunit.core' instead?

### ISSUE THREAD

**Issue by cmeeren** [hedgehogqa/fsharp-hedgehog-xunit#13]
Does this package need to rely on `xunit`, and not just `xunit.core` (or `xunit.abstractions`, which it currently relies on)?

Asking because I only reference `xunit.core` v2.4.2 in my test project (it's all I need), but I was then unable to install `Hedgehog.Xunit` because it tried to install `xunit` 2.4.1, causing a version conflict. (I was able to work around it by installing `xunit` 2.4.2 explicitly, but unless `Hedgehog.Xunit` needs that specific package, it seems unnecessary.)

**Comment by AlexErrant** [comment]
Yeah it builds for me with just `xunit.core`. Gimme a bit to figure out some nonsense with my NuGet API key and I'll cut a new release.

**Comment by dharmaturtle** [comment]
Should be fixed with [0.5.2](https://www.nuget.org/packages/Hedgehog.Xunit/#dependencies-body-tab).
