### ISSUE TITLE
Is Hedgehog.Xunit mostly useful when there are few test-specific invariants or other requirements for test parameters?

### ISSUE THREAD

**Issue by cmeeren** [hedgehogqa/fsharp-hedgehog-xunit#15]
I find that in most of my tests, the set of test parameters have invariants that must be satisfied. For example, the property `Foo` of the object in the second argument must be larger than the value in first argument. Not to mention that in many tests, values must satisfy some criteria – for example, a value must be positive in order for the test to make sense.

I am used to the `property { ... }` computation expression, where I generate one value at a time and can specify the exact requirements for each value. Thess requirements may be based on previously generated values, in order to preserve invariants in the whole set of values.

Based on the readme in this repo, I understand how to accomplish the same with Hedgehog.Xunit using `AutoGenConfig`. However, if I am to define a separate generator config for more or less every test function, then I don't really see the benefit over simply using `property { ... } |> Property.check` and generating all values inside there.

Furthermore, to get the same flexibility with Hedgehog.Xunit (specifically, if multiple arguments have the same type but different requirements, such as one positive and one negative integer), I would need to wrap the arguments in a custom type (e.g. a record) to be able to enforce the necessary invariants.

This leads me to believe that Hedgehog.Xunit is mostly useful if one only rarely has test-specific invariants or other requirements for test parameters.

Does that make sense (and do you agree), or have I missed something?

**Comment by TysonMN** [comment]
That sounds right to me.

@dharmaturtle?

**Comment by dharmaturtle** [comment]
Yup! Most of the tests I was using it for were round-trip-style tests, where I give it good data, and assert that the data hasn't changed after a series of function (e.g. serialization/deserialization). I would sometimes generate good data then intentionally break an invariant by setting a property to, say, `null` and assert that an error would occur.

**Comment by TysonMN** [comment]
@dharmaturtle, why can't I close this issue?

**Comment by dharmaturtle** [comment]
Not sure - I can though. I'm not sure what the Hedgehog github-org permissions look like, but it seems like I still retain enough permissions.

**Comment by dharmaturtle** [comment]
FYI [0.6.0](https://www.nuget.org/packages/Hedgehog.Xunit/0.6.0) adds `GenAttribute` which allows you to set generators for individual test parameters.
