### ISSUE TITLE
Should we move the project to core @hedgehogqa?

### ISSUE THREAD

**Issue by moodmosaic** [hedgehogqa/fsharp-hedgehog-xunit#8]
/cc @TysonMN

The project's current state looks awesome, and from what I can tell from its README, feature complete. Moving it into the core org would make it more discoverable :rocket:

**Comment by dharmaturtle** [comment]
Done! Way less painful than I anticipated.

**Comment by moodmosaic** [comment]
Awesome 👌❤️
